name       : nghttp2
version    : 1.32.0
release    : 3
source     :
    - https://github.com/nghttp2/nghttp2/releases/download/v1.32.0/nghttp2-1.32.0.tar.xz : 700a89d59fcc55acc2b18184001bfb3220fa6a6e543486aca35f40801cba6f7d
license    : MIT
component  : system.base
summary    : HTTP/2 C Library
description: |
    This is an implementation of the Hypertext Transfer Protocol version 2 in C.
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(libevent_openssl)
    - pkgconfig(openssl)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
