name       : nghttp2
version    : 1.41.0
release    : 8
source     :
    - https://github.com/nghttp2/nghttp2/releases/download/v1.41.0/nghttp2-1.41.0.tar.xz : abc25b8dc601f5b3fefe084ce50fcbdc63e3385621bee0cbfa7b57f9ec3e67c2
license    : MIT
component  : system.base
summary    : HTTP/2 C Library
description: |
    This is an implementation of the Hypertext Transfer Protocol version 2 in C.
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(libevent_openssl)
    - pkgconfig(openssl)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
